
name: FASTEN_CI_Manual_Dependencies_Download

on: [push, pull_request]

env:
  MPS_VER: "2020.3"
  MPS_ZIP: "http://download.jetbrains.com/mps/2020.3/MPS-2020.3.4.zip"
  JBR: "https://bintray.com/jetbrains/intellij-jbr/download_file?file_path=jbr-11_0_7-windows-x64-b765.57.tar.gz"
  FASTEN_DISTRIBUTION_PACKAGE: "/home/runner/work/mbeddr.formal/mbeddr.formal/build/artifacts/com.mbeddr.formal.safetyDistribution/fasten-1.0-SNAPSHOT.zip"
  FASTEN_DISTRIBUTION_DIR: "/home/runner/work/mbeddr.formal/mbeddr.formal/build/fasten-1.0-SNAPSHOT"
  ANALYZERS_DIR: "/home/runner/work/mbeddr.formal/mbeddr.formal/rcp_resources/external_tools"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DISPLAY: ':99'

    steps:
    - uses: actions/checkout@v2

    - name: Download Dependencies
      run: |
        chmod +x ./dependencies_downloader.sh
        ./dependencies_downloader.sh

    - name: Set up Gradle
      run: |
        chmod +x ./gradlew
        
    - name: Setup headless environment
      run: |
        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
       
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11  
        
    - name: Build FASTEN
      uses: eskatos/gradle-command-action@v1.3.3
      with: 
        arguments: -b build_ci.gradle build_fasten_safety_distribution -Dorg.gradle.internal.http.connectionTimeout=650000 -Dorg.gradle.internal.http.socketTimeout=650000 -Pgpr.user=${{github.actor}} -Pgpr.token=${{ secrets.GITHUB_TOKEN }}
        wrapper-cache-enabled: true
        dependencies-cache-enabled: true
        dependencies-cache-key: gradle/dependency-locks/**
        dependencies-cache-exact: true
        configuration-cache-enabled: true
        gradle-executable: /home/runner/work/mbeddr.formal/mbeddr.formal/gradlew

    - name: Get Current Time
      id: time
      uses: nanzm/get-time-action@v1.1
      with:
        timeZone: 2
        format: 'YYYY-MM-DD-HH-mm'
    - name: Archive distribution
      uses: actions/upload-artifact@v2
      with:
        name: fasten-distribution-2020.3-${{ steps.time.outputs.time }}
        path: build/artifacts/com.mbeddr.formal.safetyDistribution/fasten-2020.3-SNAPSHOT.zip
